name: Build and push container image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    permissions:
      id-token: write
    strategy:
      matrix:
        runner: ["ubuntu-latest", "ubicloud-standard-8-arm"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Login to Stackable Harbor
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: oci.stackable.tech
          username: robot$stackable+github-action-build
          password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
      - name: Set up Cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # tag=v3.5.0
      - name: Determine Architecture
        run: |
          echo "TAG=$(arch)" >> "$GITHUB_ENV"
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: oci.stackable.tech/stackable/mergebom:${{ env.TAG }}
      - name: Sign the published image
        run: cosign sign -y oci.stackable.tech/stackable/mergebom@${{ steps.build-and-push.outputs.digest }}
  create_manifest:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: ["build_image"]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Login to Stackable Harbor
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: oci.stackable.tech
          username: robot$stackable+github-action-build
          password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
      - name: Set up Cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
      - name: Build Manifest List
        shell: bash
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          MANIFEST_LIST_NAME=oci.stackable.tech/stackable/mergebom
          docker manifest create "$MANIFEST_LIST_NAME:latest" "$MANIFEST_LIST_NAME:x86_64" "$MANIFEST_LIST_NAME:aarch64"
          # `docker manifest push` directly returns the digest of the manifest list
          # As it is an experimental feature, this might change in the future
          # Further reading: https://docs.docker.com/reference/cli/docker/manifest/push/
          DIGEST=$(docker manifest push "$MANIFEST_LIST_NAME:latest")
          # Refer to image via its digest (oci.stackable.tech/sdp/airflow@sha256:0a1b2c...)
          # This generates a signature and publishes it to the registry, next to the image
          # Uses the keyless signing flow with Github Actions as identity provider
          cosign sign -y "$MANIFEST_LIST_NAME@$DIGEST"